#cloud-config

# Install additional packages on first boot
#
# Default: none
#
# if packages are specified, this package_update will be set to true
#
# packages may be supplied as a single package name or as a list
# with the format [<package>, <version>] wherein the specific
# package version will be installed.
packages:
  - curl
  - git
  - htop
  - jq
  - ncdu
  - net-tools
  - qemu-guest-agent
  - tmux
  - tree
  - vim
  - zsh
timezone: Asia/Tehran
