#cloud-config

packages:
  - curl
  - git
  - htop
  - jq
  - ncdu
  - net-tools
  - nfs-common
  - open-vm-tools
  - tmux
  - tree
  - vim
package_update: true
package_upgrade: true
package_reboot_if_required: true
timezone: Asia/Tehran
